### ISSUE TITLE
Add feature to specify liquid by name for a port instead of defining all its parameters

### ISSUE THREAD

**Issue by jsreid13** [manifold-lang/pymanifold#2]
Currently when defining a port you only have the option of providing the parameters of the liquid individually where it would be nice to be able to say something like ```Schematic.port('in', 'input', liquid='water')``` and internally it uses the standard density, viscosity, and in the future, resistivity of water for calculations as this is more user friendly. This requires adding a new argument to the port method called liquid (or whatever name you like) and have it default to nothing, but if a liquid is provided to see if it's part of the supported liquids, if not throw an error and list the valid liquids. If it's valid then set min_viscosity, min_density to the correct value, and add min_resistivity and set that to the correct values. Do this for a water, mineral oil and polyacrylamide used in gel electrophoresis.

**Comment by VermaSh** [comment]
I have add the feature to [my fork](https://github.com/VermaSh/pymanifold/commit/c5c31a2a3c0fec5eda64d0f1244bb8a3cef39cd6). However, I couldn't find resistivity for polyacrylamide. Is there a particular fluid name I should be searching for?

**Comment by jsreid13** [comment]
I found [this paper](https://onlinelibrary.wiley.com/doi/full/10.1002/app.27716) that talks about making more conductive polyacriamide and [includes a graph for just regular polyacryamide as a control](https://wol-prod-cdn.literatumonline.com/cms/attachment/7e0fb4dc-012e-4c06-9e12-fbd6206ae72c/mfig003.jpg), in this case they measure conductivity instead of resistivity but since they're reciprocals of each other its easy to convert between the two. Interestingly it looks like the conductivity of polyacrylamide depends on the concentrations of the reactants used to make it. Looks like the the concentration is usually pretty low [[1]](http://ivaan.com/protocols/112.html) , a bit lower than what they used in this graph so I think we should just use the lowest value of 0.07 mS/cm (or 14.28 kOhm*cm) for now, I'll update you after talking to Prof. Backhouse to see if he has a better number in mind.
